### ISSUE TITLE
Alternate File command broken when file creation required

### ISSUE THREAD

**Issue by smartygus** [rspec/rspec.tmbundle#104]
I've encountered a problem with the bundle version based on the most recent [commit](https://github.com/rspec/rspec.tmbundle/commit/41cf1b2cf84a9579c04da658857560ad1ec20551) implementing TM_RSPEC_BASEDIR. The problem is while using the Alternate File command - it generates an error when it tries to create the alternate file:  

```
[...]/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/switch_command.rb:145:in `write_and_open': undefined local variable or method `base_dir' for #<RSpec::Mate::SwitchCommand:0x10bf2ab78> (NameError)
from [...]/Library/Application Support/TextMate/Managed/Bundles/RSpec.tmbundle/Support/lib/rspec/mate/switch_command.rb:21:in `go_to_twin'
from Alternate File:4
```

The command still works fine if the alternate file already exists.

The problem stems from some [code](https://github.com/rspec/rspec.tmbundle/blob/41cf1b2cf84a9579c04da658857560ad1ec20551/Support/lib/rspec/mate/switch_command.rb#L142) in the `switch_command.rb` file, which attempts to use a helper method (`base_dir`) from `helpers.rb`, but this file is not required in `switch_command.rb`, meaning this method is not available.

I thought it would be a simple matter of just requiring the file, but:

All the other files that use the `base_dir` helper method simply require the helpers file using `require_relative`, but seeing as the Alternate File command [uses the ruby18 shim](https://github.com/rspec/rspec.tmbundle/blob/41cf1b2cf84a9579c04da658857560ad1ec20551/Commands/Alternate%20File.tmCommand#L8), `require_relative` is not available.

I tried requiring the helpers file using alternate methods I found while googling that are supposed to work with Ruby 1.8, but I still got errors saying that the `base_dir` method is not defined (I started using Ruby after 1.8 was already obsolete, so my knowledge here is admittedly a bit thin).

So I guess if someone knows how to get this file properly required in a ruby1.8 way, so that the helper method is available, then this should fix the problem. But I'm afraid I hit a brick wall.

**Comment by noniq** [comment]
Good catch and thorough examination, thanks!

Seems like we have to stick to Ruby 1.8 for Commands run from TextMate (see http://lists.macromates.com/textmate-dev/2014-August/014993.html – note that the `ruby20` has not yet been implemented, as far as I can tell).

A backward compatible replacement for `require_relative` would be `require File.dirname(__FILE__) + "/foo.rb"`, I think.
 
Ccing @infininight.

**Comment by smartygus** [comment]
Yeah, I saw that TextMate wasn't ready for Ruby2.0 yet either, which is a bit of a bummer, but what can you do...

I actually tried a few different options, and I couldn't get any of them to work. Not sure if it's something to do with my setup though. Here's what I tried:-
```ruby
require File.expand_path(File.dirname(__FILE__) + '/helpers.rb')
# or
require File.dirname(__FILE__) + "/helpers.rb"
# or
$LOAD_PATH << File.dirname(__FILE__) # followed by...
require 'helpers'
```

**Comment by noniq** [comment]
All of these should have worked correctly :) But you also need to add `include Helpers` to make the method available :)

**Comment by smartygus** [comment]
Oh haha, of course!
Kinda doesn't work without being included 😅
Thanks
